[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".local/bin/mise"]
  type = "file"
  url = "https://mise.jdx.dev/mise-latest-linux-x64"
  exact = true
  refreshPeriod = "168h"


